name: Build VortLang

on:
  push:
    paths:
      - 'lang/**'
  pull_request:
    paths:
      - 'lang/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: set up rust
        uses: actions/setup-rust@v1
        with:
          rust-version: stable

      - name: build VortLang
        run: cargo build --release
        working-directory: lang

      - name: run tests
        run: cargo test
        working-directory: lang
